### PR TITLE
From ts to js

### PR DESCRIPTION
**Pull request by u-rogel**
A few major changes on this branch:
1. Since it seems like no one wants to deal with TS I converted all files to JS.
2. package.json was updated to latest react version.
3. ESLint was added as well, in order to force better JS coding style.
4. Many cosmetics were done to meet the modern react project structure.

### CODE REVIEW

**Comment by tomsrocket** [comment]
I got google security warnings on my Google account because there is a Google API key in the Sourcecode.. 
However, it looks like that key has always been there..
¯\_(ツ)_/¯

**Comment by u-rogel** [comment]
I don't see any Google API Key in the code, and I haven't added or used any as far as I know.
Do you see it in the pull request as well?
I will resolve the conflict and push again.

**Comment by Sijoma** [comment]
This is sad :(. TypeScript is awesome!

**Comment by u-rogel** [comment]
Are you guys still working often on the frontend of this app?

**Comment by ubergesundheit** [comment]
I guess no one is really working actively on this right now, so for me this is awesome!

I didn't had time to look at every change but I guess it should be mostly changes done by eslint?

One thing does not work on the deploy preview https://deploy-preview-81--mein-ms.netlify.com -> Loading Data :D

**Pull request merged**
