### PR TITLE
Figma design

### PR DESCRIPTION
**Pull request by u-rogel**
Added a horizontal scroll bar for categories
Search term are matching also case-insensitive

### CODE REVIEW

**Review by ubergesundheit — APPROVED** [review]

**Comment by ubergesundheit** [comment]
Looks good, should I merge? @tomsrocket your opinion?

**Comment by u-rogel** [comment]
@ubergesundheit should I merge it or are we still awaiting further feedback?

**Comment by ubergesundheit** [comment]
Lets wait for a review of @tomsrocket

**Review by tomsrocket — APPROVED** [review]
I havent worked with styled components before, and my React knowledge has faded a bit .. so .. looks good to me

**Pull request merged**
